# Test the min and max functions

# Test min function with integers
print("Testing min function with integers:")
print("min(5, 10) =")
print(min(5, 10))
print("min(10, 5) =")
print(min(10, 5))
print("min(-5, 5) =")
print(min(-5, 5))
print("min(5, 5) =")
print(min(5, 5))

# Test min function with floats
print("\nTesting min function with floats:")
print("min(5.5, 10.5) =")
print(min(5.5, 10.5))
print("")
print("min(10.5, 5.5) =")
print(min(10.5, 5.5))
print("")
print("min(-5.5, 5.5) =")
print(min(-5.5, 5.5))
print("")
print("min(5.5, 5.5) =")
print(min(5.5, 5.5))

# Test max function with integers
print("\nTesting max function with integers:")
print("max(5, 10) =")
print(max(5, 10))
print("max(10, 5) =")
print(max(10, 5))
print("max(-5, 5) =")
print(max(-5, 5))
print("max(5, 5) =")
print(max(5, 5))

# Test max function with floats
print("\nTesting max function with floats:")
print("max(5.5, 10.5) =")
print(max(5.5, 10.5))
print("")
print("max(10.5, 5.5) =")
print(max(10.5, 5.5))
print("")
print("max(-5.5, 5.5) =")
print(max(-5.5, 5.5))
print("")
print("max(5.5, 5.5) =")
print(max(5.5, 5.5))

# Test with mixed types (should coerce to float)
print("\nTesting with mixed types:")
print("min(5, 10.5) =")
print(min(5, 10.5))
print("")
print("max(5, 10.5) =")
print(max(5, 10.5))
